export type ItemType =
    | 'Generic'
    | 'MainHand'
    | 'OffHand'
    | 'BodyArmor'
    | 'Helmet'
    | 'Boots'
    | 'Gloves'
    | 'Belt'
    | 'Amulet'
    | 'Ring'
    | 'Gold'
    | 'Xp'
    | 'Consumable'
    | 'Map';
